### ISSUE TITLE
SFT Marketplace の　Roadmap(仮)

### ISSUE THREAD

**Issue by 0xkf** [kohei-fujii/ToDo#299]
- [ ] NFTの分割所有
- [ ] 不動産の分割所有

ベンチマークは、BTCの取引所など。
チェーンは、EVM＝＞独自チェーンを想定。
Solanaなどの資本呼べそうなら、はじめにそこを挟むのも、可能だが、いかに？？？

- [ ] Fix title
- [ ] Ask in Slack
- [ ] JIRA issued
- [ ] Prepare with the organizer
- [ ] Setting the goal
- [ ] [Slides]()
- [ ] Movies preparation
- [ ] The day!
- [ ] PDF release in SlideShare
- [ ] Publish the movie
- [ ] Subtitle to the movide
- [ ] Publish the blog
