### ISSUE TITLE
checklist for start of the year

### ISSUE THREAD

**Issue by 0xkf** [kohei-fujii/ToDo#562]
- [x] object
- [x] class
- [x] hairetu
- [x] export
- [ ] promise
- [x] async, await
- [x] typescript-type
- [x] ===================================================================
- [x] <task-in-the first week>
- [x] web3.js-uses
- [x] execute GCP
- [x] ====================================================================
- [ ] D3.js-test
- [x] zkrollup-test
- [x] issue-nft
- [ ] gameFi-test
- [ ] L2-codecheck(zkSync,Scroll,Intmax,Starknet,）
- [x] Layer1-technicalresearch
- [ ] 
- [x] PDF release in SlideShare
- [x] Publish the movie
- [x] Subtitle to the movide
- [x] Publish the blog

**Comment by 0xkf** [comment]
D3.jsと、L2のコードチェック、あとは、gameFiの実験だけ残してdone
