### ISSUE TITLE
checklist for January

### ISSUE THREAD

**Issue by 0xkf** [kohei-fujii/ToDo#627]
- [x] tax-yanagisan
- [x] inves-rel-Hsan
- [x] Osaka-issue
- [x] └osakapol
- [x] └osakatihou
- [x] job-rel
- [ ]└gcompany-rel
- [x] └sft-ichizen
- [x] └dev-fx
- [ ] └dev-L2
- [ ] └onchaingame-rel
- [ ] └water-dao-rel
- [x] 
- [x] Prepare with the organizer
- [x] Setting the goal
- [x] [Slides]()
- [x] Movies preparation
- [x] The day!
- [x] PDF release in SlideShare
- [x] Publish the movie
- [x] Subtitle to the movide
- [ ] Publish the blog
