### ISSUE TITLE
Todo @Osaka

### ISSUE THREAD

**Issue by 0xkf** [kohei-fujii/ToDo#972]
- [x] go back 17
- [x] omiyage sinseki 17
- [x] meet family17
- [x] haru meetup 18
- [x] go to ohakamairi 18

- [ ] headphone kaisyuu19 　=>waiting for Tomi
- [x] uniqlo 19 15:00-
- [x] docomo 19 16:00 -
- [ ] buy iphone  SE 19 => waiting for coming @ 3/21　＝＞I may cancel when the new phone came...
- [x] eat steak 18:00-
- [x] football @ Osaka 20 :00-22:00
- [x] take a bath??

- [x] kitakuyakusyo 20 9:00-
- [x] はし本 20 12:00-
- [x] reply Kyoto University,,,
- [x] sister-misa 20 16:00-
- [x] iphone 8 will come

- [x] WBC 21 7:55-  vs Mexico
- [x] ohinasan from 3FSouko 21 
- [x] hanami??＝＞raning that...
- [x] play football 

- [ ] iphone SE will come 21 => we will return the one...
- [x] eat luch with grandfather 18.19,21
- [ ] inarikun??　yuugata,Osaka?
- [x] 
- [ ] WBC 22 
- [ ] take mother to the hospital 22

- [ ] meet inarikun 19-22
- [ ] eat lunch with grandfather 18??

- [ ] go to Kyoto　23,24
- [ ] stay @ kawaramati 23
- [ ] hanami 23
- [ ] kyodai 23
- [ ] toudaikinyuuken 23
- [ ] meeting kazsan 23
- [ ]

- [ ] stay @ sijyo hanami  24
- [ ] nijyojyo 24 
- [ ] mother may come..?

- [ ] go back to Tokyo 25
- [ ] kaihuu? yuugata  25

- [ ] hanami with Jojisan 26 
- [ ] panna 14:00-? @ sky tree
- [ ]
